# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: da3feb44d051fa998f1c1d46fd3f4d0876a75399e60916baea582ea14c0197de3126f3423492b103dd12df255a8131cbb9ed976e46872096e31c336b0e68cad7

test:
  secret_key_base: 0194086ae6557d688ecd681c6fd5570b88052158053c0c2f6e74ef457fb1a0357678b501686b756e5022e444e68d51bbfa87c69b2c81ce2081cbded57e45891e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
